### ISSUE TITLE
remove me from game

### ISSUE THREAD

**Issue by MinimalMio** [minqwq/minqwq-life#1]
No reason

**Comment by Rongxuan2022** [comment]
我有意见。

**Comment by MinimalMio** [comment]
no you have no opinion

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rongxuan2022** [comment]
**你走=游戏不完整**

**Comment by MinimalMio** [comment]
(。・`ω´・)

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Rongxuan2022** [comment]
min哪去了救一下啊

**Comment by minqwq** [comment]
...no reason?

**Comment by MinimalMio** [comment]
y

________________________________

**Comment by minqwq** [comment]
btw
你是这里头的核心人物
没你我可能续不下去剧情

**Comment by MinimalMio** [comment]
![IMG_20240921_104610_406](https://github.com/user-attachments/assets/30f27dfa-0956-4475-9bda-5868e4901cd8)
