### ISSUE TITLE
有一个音乐没加

### ISSUE THREAD

**Issue by Meltide** [minqwq/minqwq-life#3]
Chapter1-3因为一个名为Year-Round_Absorbed_Curiosity_Chiptune_remix_and_no_main_melody__--_minqwq.mp3音乐没有加入崩溃了
![Screenshot_2024-10-20-10-31-10-130_com termux-edit](https://github.com/user-attachments/assets/172b2941-2a50-4dc9-ac85-2bcd7b71b62d)

**Comment by minqwq** [comment]
再试试
应该加上了

于 2024年10月20日 GMT+08:00 上午10:32:12，Meltide ***@***.***> 写道：
>Chapter1-3因为一个名为Year-Round_Absorbed_Curiosity_Chiptune_remix_and_no_main_melody__--_minqwq.mp3音乐没有加入崩溃了
>![Screenshot_2024-10-20-10-31-10-130_com termux-edit](https://github.com/user-attachments/assets/172b2941-2a50-4dc9-ac85-2bcd7b71b62d)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/minqwq/minqwq-life/issues/3
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
--minqwq
